language: android

jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-24
      ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - $ANDROID_TARGET
    - sys-img-$ANDROID_ABI-$ANDROID_TARGET
    - extra

before_script: # Create and start emulator
  - android list targets
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest
  - ./gradlew createDebugCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
